version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  devops-node:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
    - NODE_ENV=development
    - MONGO_USER=kabigon
    - MONGO_PASSWORD=mysecurepassword121
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kabigon  
      - MONGO_INITDB_ROOT_PASSWORD=mysecurepassword121
