version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  devops-node:
    build: .
    environment:
    - PORT=3000
    depends_on:
    - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kabigon  
      - MONGO_INITDB_ROOT_PASSWORD=mysecurepassword121
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: